version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.02

    environment:
      DOCKER_REGISTRY: docker.pkg.github.com
      DOCKER_REGISTRY_USERNAME: mahoney-playground
      DOCKER_REPO: mahoney-playground/goos
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain

    steps:
      - setup_remote_docker:
          version: 18.09.3
      - checkout
      - run:
          name: docker login
          command: |
            echo "$DOCKER_REGISTRY_PASSWORD" | \
            docker login --username "$DOCKER_REGISTRY_USERNAME" --password-stdin $DOCKER_REGISTRY
      - run: docker build --target app -t goos-app:${CIRCLE_SHA1} .
      - run: docker build --target tests -t goos-tests:${CIRCLE_SHA1} .
      - run: docker build --target builder -t goos-builder:${CIRCLE_BRANCH} .'
