version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.02

    environment:
      DOCKER_REPO: mahoney-playground/goos
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain

    steps:
      - setup_remote_docker:
          version: 18.09.3
      - checkout
      - run: docker login --username "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY < <(echo "$DOCKER_PASSWORD")
      - run: docker build -t goos-app:${CIRCLE_SHA1} .
      - run: docker build --target tests -t goos-tests:${CIRCLE_SHA1} .

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: 'Docker GitHub'
