version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.02
        version: 18.09.3
    steps:
      - setup_remote_docker
      - checkout
      - run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up --build
