version: '2.4'

services:

  auctionhost.internal:
    image: ghcr.io/mahoney-playground/openfire:4.5.1
    hostname: auctionhost.internal
    build:
      context: ../../../docker-openfire

  auction-xmpp-integration-tests:
    image: ghcr.io/mahoney-playground/goos-auction-xmpp-integration-tests:${GOOS_TAG:?"You must set GOOS_TAG"}
    command: --disable-banner --reports-dir=build/reports
    depends_on:
      auctionhost.internal:
        condition: service_healthy
    build:
      context: ../../..
      target: auction-xmpp-integration-tests
