@file:Suppress("unused")

const val kotlinVersion = "1.4.0"
fun kotlinCoroutines(module: String) = "org.jetbrains.kotlinx:kotlinx-coroutines-$module:1.3.9"
fun kotest(module: String) = "io.kotest:kotest-$module:4.2.2"
fun arrow(module: String) = "io.arrow-kt:arrow-$module:0.10.5"
fun smack(module: String) = "org.igniterealtime.smack:smack-$module:4.3.4"
fun jxmpp(module: String) = "org.jxmpp:jxmpp-$module:0.6.4"
private const val mockkVersion = "1.10.0"
fun mockk(module: String) = "io.mockk:mockk-$module:$mockkVersion"
const val mockk = "io.mockk:mockk:$mockkVersion"
fun kotlinxHtml(module: String) = "org.jetbrains.kotlinx:kotlinx-html-$module:0.7.2"
fun marathon(module: String) = "com.jaliansystems:marathon-$module:5.2.6.0"
const val byteBuddy = "net.bytebuddy:byte-buddy:1.10.9"
fun selenium(module: String) = "org.seleniumhq.selenium:selenium-$module:3.14.0"
