version: '3.7'

services:

  auctionhost:
    hostname: auctionhost
    build:
      context: ../docker-openfire

  app:
    image: docker.pkg.github.com/mahoney-playground/goos/goos-app:${GOOS_TAG:?"You must set GOOS_TAG"}
    init: true
    build:
      context: ..
      target: app

  end-to-end-tests:
    image: docker.pkg.github.com/mahoney-playground/goos/goos-end-to-end-tests:${GOOS_TAG:?"You must set GOOS_TAG"}
    command: --disable-banner --reports-dir=build/reports
    init: true
    depends_on:
      - app
      - auctionhost
    build:
      context: ..
      target: end-to-end-tests
