version: '2.4'

services:

  auctionhost.internal:
    image: ghcr.io/mahoney-playground/openfire:4.5.1
    hostname: auctionhost.internal
    build:
      context: ../docker-openfire

  app.internal:
    image: ghcr.io/mahoney-playground/goos-instrumentedapp:${GOOS_TAG:?"You must set GOOS_TAG"}
    command: auctionhost.internal sniper sniper
    build:
      context: ..
      target: instrumentedapp

  end-to-end-tests:
    image: ghcr.io/mahoney-playground/goos-end-to-end-tests:${GOOS_TAG:?"You must set GOOS_TAG"}
    command: --disable-banner --reports-dir=build/reports
    depends_on:
      auctionhost.internal:
        condition: service_healthy
      app.internal:
        condition: service_healthy
    build:
      context: ..
      target: end-to-end-tests
