version: '3.7'

services:
  app:
    image: docker.pkg.github.com/mahoney-playground/goos/goos-app:$GOOS_TAG
    build:
      context: ..
      target: app

  tests:
    image: docker.pkg.github.com/mahoney-playground/goos/goos-tests:$GOOS_TAG
    build:
      context: ..
      target: tests
