name: Docker Image CI

on:
  push:
    branches-ignore:
      - 'abandoned-*'

env:
  DOCKER_REPO: ghcr.io/mahoney-playground

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Do the build
        run: docker build .
