name: Docker Image CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * *'

env:
  DOCKER_REPO: mahoney-playground/goos
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache docker
      uses: actions/cache@v1
      if: github.event_name != 'schedule'
      env:
        cache-name: docker-cache-1
      with:
        path: ${{ runner.temp }}/docker_cache
        key: ${{ env.cache-name }}-${{ github.run_number }}
        restore-keys: |
          ${{ env.cache-name }}-

    - name: Restore docker
      run: ./.github/actions/docker-cache/restore.sh ${{ runner.temp }}/docker_cache/cache.tar

    - name: Build App with Docker
      run: docker build . --target app -t goos-app:$GITHUB_SHA

    - name: Build Tests with Docker
      run: docker build . --target tests -t goos-tests:$GITHUB_SHA

    - name: Backup docker
      run: ./.github/actions/docker-cache/backup.sh ${{ runner.temp }}/docker_cache/cache.tar

  end-to-end-tests:
    needs: build
    runs-on: ubuntu-18.04

    steps:
      - name: Run end to end tests
        run: GOOS_TAG=$GITHUB_SHA docker-compose up --no-build --exit-code-from tests
