name: Docker Image CI

on: [push]

env:
  DOCKER_REPO: mahoney-playground/goos
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Cache docker
      uses: actions/cache@v1
      env:
        cache-name: mahoney-playground-goos-cache-docker-2
      with:
        path: ~/docker-cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Replace docker cache
      run: sudo cp -r ~/docker-cache/* /var/lib/docker/
      shell: bash

    - name: Build App with Docker
      run: docker build . -t goos-app:${GITHUB_SHA}
      shell: bash

    - name: Build Tests with Docker
      run: docker build . --target tests -t goos-tests:${GITHUB_SHA}

    - name: Size of docker
      run: docker system df

    - name: Replace docker cache
      run: sudo cp -r /var/lib/docker/ ~/docker-cache/*
      shell: bash
