name: Docker Image CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * *'

env:
  DOCKER_REPO: mahoney-playground/goos
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  cache-name: docker-cache-1

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache docker
      uses: actions/cache@v1
      if: github.event_name != 'schedule'
      with:
        path: ${{ runner.temp }}/docker_cache
        key: ${{ env.cache-name }}-${{ github.run_number }}
        restore-keys: |
          ${{ env.cache-name }}-

    - name: Restore docker
      run: ./.github/actions/docker-cache/restore.sh ${{ runner.temp }}/docker_cache/cache.tar

    - name: Login to docker repo
      run: docker login --username Mahoney-playground --password-stdin docker.pkg.github.com < <(echo "${{ secrets.GITHUB_TOKEN }}")

    - name: Do the build
      run: docker build . --target builder -t goos-builder:$GITHUB_SHA

    - name: Capture the reports as artifacts
      run: container_id=$(docker create goos-builder:$GITHUB_SHA) &&
           mkdir -p ${{ runner.temp }}/reports/core/reports &&
           docker cp "$container_id":/home/worker/work/core/build/reports ${{ runner.temp }}/reports/core/reports &&
           mkdir -p ${{ runner.temp }}/reports/end-to-end-tests/reports &&
           docker cp "$container_id":/home/worker/work/end-to-end-tests/build/reports ${{ runner.temp }}/reports/end-to-end-tests/reports

    - name: Archive reports
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: ${{ runner.temp }}/reports

    - name: Check the build passed
      run: docker build . --target checker

    - name: Build App with Docker
      run: docker build . --target app -t docker.pkg.github.com/${{ env.DOCKER_REPO }}/goos-app:$GITHUB_SHA &&
           docker push docker.pkg.github.com/${{ env.DOCKER_REPO }}/goos-app:$GITHUB_SHA

    - name: Build Tests with Docker
      run: docker build . --target tests -t docker.pkg.github.com/${{ env.DOCKER_REPO }}/goos-tests:$GITHUB_SHA &&
           docker push docker.pkg.github.com/${{ env.DOCKER_REPO }}/goos-tests:$GITHUB_SHA

    - name: Backup docker
      run: ./.github/actions/docker-cache/backup.sh ${{ runner.temp }}/docker_cache/cache.tar

  end-to-end-tests:
    needs: build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Login to docker repo
      run: docker login --username Mahoney-playground --password-stdin docker.pkg.github.com < <(echo "${{ secrets.GITHUB_TOKEN }}")

    - name: Run end to end tests
      env:
        GOOS_TAG: ${{ github.sha }}
      run: cd end-to-end-tests &&
           docker-compose pull &&
           docker-compose up --no-build --exit-code-from tests
