name: Docker Image CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * *'

env:
  DOCKER_REPO: mahoney-playground/goos
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  cache-name: docker-cache-5

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache docker
      uses: actions/cache@v1
      if: github.event_name != 'schedule'
      with:
        path: ${{ runner.temp }}/docker_cache
        key: ${{ env.cache-name }}-${{ github.run_number }}
        restore-keys: |
          ${{ env.cache-name }}-

    - name: Restore docker
      run: ./.github/actions/docker-cache/restore.sh ${{ runner.temp }}/docker_cache/cache.tar

    - name: Login to docker repo
      run: docker login --username Mahoney-playground --password-stdin docker.pkg.github.com < <(echo "${{ secrets.GITHUB_TOKEN }}")

    - name: Do the build
      run: docker build . --target builder -t goos-builder:$GITHUB_SHA

    - name: Capture the reports as artifacts
      run: container_id=$(docker create goos-builder:$GITHUB_SHA) &&
           mkdir -p builds/${{ github.sha }} &&
           docker cp "$container_id":/home/worker/work/build/reports builds/${{ github.sha }} &&
           mv builds/${{ github.sha }}/reports builds/${{ github.sha }}/build-reports

    - name: Archive reports
      uses: actions/upload-artifact@v1
      with:
        name: build-reports
        path: builds/${{ github.sha }}/build-reports

    - name: Publish Reports
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: builds
        TARGET_FOLDER: builds

    - name: Link to Reports
      run: echo "Reports are published at https://mahoney-playground.github.io/goos/builds/${{ github.sha }}/build-reports"

    - name: Build End to End Tests with Docker
      run: docker build . --target end-to-end-tests -t docker.pkg.github.com/${{ env.DOCKER_REPO }}/goos-end-to-end-tests:$GITHUB_SHA &&
           docker push docker.pkg.github.com/${{ env.DOCKER_REPO }}/goos-end-to-end-tests:$GITHUB_SHA

    - name: Build App with Docker
      run: docker build . --target instrumentedapp -t docker.pkg.github.com/${{ env.DOCKER_REPO }}/goos-instrumentedapp:$GITHUB_SHA &&
           docker push docker.pkg.github.com/${{ env.DOCKER_REPO }}/goos-instrumentedapp:$GITHUB_SHA

    - name: Build openfire with Docker
      run: cd docker-openfire && docker build . -t docker.pkg.github.com/${{ env.DOCKER_REPO }}/openfire:4.5.1 &&
           docker push docker.pkg.github.com/${{ env.DOCKER_REPO }}/openfire:4.5.1

    - name: Backup docker
      run: ./.github/actions/docker-cache/backup.sh ${{ runner.temp }}/docker_cache/cache.tar

  end-to-end-tests:
    needs: build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Login to docker repo
      run: docker login --username Mahoney-playground --password-stdin docker.pkg.github.com < <(echo "${{ secrets.GITHUB_TOKEN }}")

    - name: Run end to end tests
      env:
        GOOS_TAG: ${{ github.sha }}
      run: cd end-to-end-tests &&
           docker-compose pull -q &&
           docker-compose up --no-build --exit-code-from end-to-end-tests --abort-on-container-exit

    - name: Capture the reports as artifacts
      if: always()
      run:
           mkdir -p builds/${{ github.sha }} &&
           docker cp end-to-end-tests_end-to-end-tests_1:/home/worker/work/build/reports builds/${{ github.sha }} &&
           mv builds/${{ github.sha }}/reports builds/${{ github.sha }}/end-to-end-tests-reports

    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: end-to-end-tests-reports
        path: builds/${{ github.sha }}/end-to-end-tests-reports

    - name: Publish Reports
      if: always()
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: builds
        TARGET_FOLDER: builds

    - name: Link to Reports
      if: always()
      run: echo "Reports are published at https://mahoney-playground.github.io/goos/builds/${{ github.sha }}/end-to-end-tests-reports"
